# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Development
host: 0.0.0.0
port: 9000

# Settings
author: "Willy Nolan"
title: "Willy Nolan"
faviconcolor: "#2cdad7"

show_exhibitions: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:title/
      category: projects
      layout: default
      class: "post video-post"

keywords: "Willy Nolan, Software Engineering, Interactive Engineering"

about:
  - "I am a software engineer focused on improving how people interact with and experience technology. This site contains some of the projects I have created while pursuing that goal."
  - "I studied Communication at Portland State University, Journalism at The University of Southern California and Computer Science at Georgia Tech."
  - "During my career I have been fortunate enough to work with companies such as Obscura Digital, TAIT, AT&T, The Madison Square Garden Company, Instagram and Snapchat on projects all over the world."
  - 'If you want to get in touch please email me: <a class="contact-link" title="willy@willynolan.com" href="mailto:willy@willynolan.com">willy@willynolan.com</a>'

exhibitions:
  - "Art Basil (Hong Kong)"
  - "Art Basil (Basil, Switzerland)"
  - "Comic-Con (San Diego, USA)"
  - "F8 Developer Conference (San Francisco, USA)"
  - "Halcyon Nightclub (San Francisco, USA)"
  - "Qasr al-Hosn Festival (Abu Dhabi, UAE)"
  - "AT&T Stadium (Dallas, USA)"
  - "Shantou University (Shantou, China)"
  - "#SF Public Canvas (San Francisco, USA)"
  - "Searching for Cydonia (San Francisco, USA)"
  - "Madison Square Garden Science Fair (London, UK)"
  - "Madison Square Garden Science Fair (Las Vegas, USA)"
  - "Madison Square Garden Science Fair (Los Angeles, USA)"

email: "willy@willynolan.com"
github: "https://github.com/computersarecool"
linkedin: "https://www.linkedin.com/in/willynolan/"
instagram: "https://www.instagram.com/computersarecool/"
